### ISSUE TITLE
Use Asset directly instead of AlternativeAsset object

### ISSUE THREAD

**Issue by lossyrob** [stac-extensions/alternate-assets#1]
The [Asset Object](https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#asset-object) in the STAC Item spec already has `href` required and all other fields optional. Do you need a specific AlterativeAsset object, or can the `alt` property be a list of Assets?

My opinion is biased based on the ease of implementation in PySTAC - if they are directly Asset objects, then the implementation that allows for users to place extension information on the Assets will be a lot simpler, something along the lines of:

```python
asset: pystac.Asset = ...
alt_asset = pystac.Asset(href="some_cloud_href")
StorageExtensions.ext(alt_asset).provider = "Macrohard"
AltAssets.ext(asset).alt = [alt_asset]
some_item.add_asset("key", asset)
```

If they are specific AlternativeAsset objects, allowing for the `StorageExtensions.ext(alt_asset).provider` bit above would be hard and potentially impossible, with another API required.

**Comment by matthewhanson** [comment]
Ah, excellent thinking. I mean, that was essentially what I seeing it as and I think it works well to just have it be a list of Assets

Since `href` is the only field required, providers would not have to repeat media type, eo:bands, etc.....which I think is nice - only provide the information that is different.  But I'm wondering how this might be accessed in downstream libraries. For instance, in stackstac or intake-stac where you specify an asset key, what is the best way to be able to specify using alternate hrefs?

**Comment by lossyrob** [comment]
Good question - I'm not sure how downstream libs will be able to specify which of the alternatives they want to use. Perhaps a reason to have alternative assets be a dict instead of a list? 😈

**Comment by matthewhanson** [comment]
Hmm, I think that's a good idea, that way each alternate is uniquely addressable. Otherwise there's have to be more complex logic, e.g., use the alternate asset that has `storage:provider=AZURE`, but there's no guarantee other fields are present.

With a dictionary you could have an optional field specifying the alternate key to use, otherwise use the default asset.  If present in the Collections's item_assets a user would see all the options for alternate when looking at the assets.
