### ISSUE TITLE
Fix JSON Schema

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/alternate-assets#5]
https://github.com/stac-extensions/alternate-assets/blob/58aa16a4f9bd04903a46d81fa91ab7e080680c44/json-schema/schema.json#L97

I'd avoid the above as it would only allow the extension to be used in 1.0.0. If there's STAC 1.0.1 once the validation would fail.

Also, there are some other flaws in the schema:
1. different schema for item_assets and assets?!
2. requiring alternate requires them for ALL assets. Is that the desired behavior?

**Comment by matthewhanson** [comment]
Ah good point, they wouldn't necessarily be required for all assets.

item_assets is different than assets because href is not required.


Without linking to asset in stac-spec, how can we validate that this is an asset?  Just duplicate all the fields from asset?  Do you think it would be worthwhile to publish "latest" JSON schemas so we could link to the latest version?

**Comment by m-mohr** [comment]
We should duplicate, yes.

**Comment by matthewhanson** [comment]
It's an awful lot of duplication, and requires pulling in info from item.json, basics.json, datetime.json, instrument.json, licensing.json, provider.json.

**Comment by matthewhanson** [comment]
I'm duplicating the fields, but not doing everything, like all the common metadata, because those are fields that would not belong in alternate anyway.

**Comment by matthewhanson** [comment]
Now that I redid the schema, I'm wondering if it's worth explicitly laying out which fields can go in 'alternate'...basically it's `href`, `title`.   `type` and `roles` should not be changed.   So that suggests this object should not technically be an "asset", but something new.

'storage' extension fields should be allowed, but if the 'alternate' object is not an Asset that means explicitly specifying storage extension fields.

Not sure the best approach. Currently it's flexible by saying that alternate is just an asset, but in the text describes that not all fields are allowed.  It's a bit nebulous and hand-wavy.   Locking it down to specified fields is more precise but won't allow the flexibility of automatically allowing new extensions to be used in 'alternate'.

**Comment by m-mohr** [comment]
What use case is there for title, type and roles? I could see some kind of value for title and roles, but if the type is different, it should be a different asset.

**Comment by matthewhanson** [comment]
That's what I trying to get at. @lossyrob suggested that alternate objects be `Asset` rather than a new type `AlternateAsset`, which means that according to the JSON schema anything in an Asset can be in an alternate object.

However, according to the README text no fields are allowed that alter the asset itself.   I can see `title` and `description`, if it were to describe the different location, e.g., "S3 Access", but `role` and `type` should not change.

I was thinking that by making it an Asset then other extensions could be used in the object. However it's a bit of a meaningless point since those will not be validated unless that extension specifically checks for the `alternate` extension.  So I can actually use `storage` in alternate, but no existing schemas will validate it.

So maybe the ideal solution is to explicitly allow specific fields: `href` (required?), `title`, `description`.  Then if another extension is able to be used here, such as `storage` it can be updated in a future version to validate alternate assets.   Validating fields from other extensions within an extension is not unprecedented since we have "item_assets" built into all the other extensions already.

**Comment by matthewhanson** [comment]
@m-mohr is the thumbs up mean you are in favor of not having the object be an `Asset` but rather an `AlternateAsset` with limited fields?

**Comment by m-mohr** [comment]
Yes, I think having it as an Asset would be pretty confusing.

**Comment by matthewhanson** [comment]
PR up that uses a new AlternateAsset object: https://github.com/stac-extensions/alternate-assets/pull/7
